version: '3.8'

networks:
  delivik-network:
    driver: bridge

services:
  postgres:
    image: postgres:15
    container_name: delivik
    environment:
      POSTGRES_USER: delivik
      POSTGRES_PASSWORD: delivik_password
      POSTGRES_DB: orders
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - delivik-network

  ui-placeholder:
    image: nginx:latest
    container_name: ui-placeholder
    ports:
      - "80:80"
    volumes:
      - ./ui-placeholder/index.html:/usr/share/nginx/html/index.html
      - ./ui-placeholder/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - delivik-network

  delivik-order-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: delivik-order-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/orders
      SPRING_DATASOURCE_USERNAME: delivik
      SPRING_DATASOURCE_PASSWORD: delivik_password
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - postgres
    networks:
      - delivik-network

volumes:
  postgres_data:
